---
- name: installing tomcat
  hosts: appserver
  become: yes
  vars:
    tomcat_download_source: "https://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.61/bin/apache-tomcat-8.5.61.zip"
    tomcat_download_location: "/tmp/apache-tomcat-8.5.61.zip"
    tomcat_install_path: "/opt/tomcat"
  tasks:
    - name: install java on ubuntu
      apt:
        name: openjdk-8-jdk
        update_cache: yes
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: add tomcat user
      user:
        name: tomcat
        home: "{{ tomcat_install_path }}"
        group: tomcat
        shell: /bin/false
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: download tomcat
      get_url:
        url: "{{ tomcat_download_source }}"
        dest: "{{ tomcat_download_location }}"
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: extract tomcat
      unarchive:
        src: "{{ tomcat_download_location }}"
        dest: "{{ tomcat_install_path }}"
      when: ansible_facts['distribution'] == "Ubuntu"
      

      
