---
- name: installing tomcat
  hosts: appserver
  become: yes
  tasks:
    - name: install java on ubuntu
      apt:
        name: openjdk-8-jdk
        update_cache: yes
        state: present
      when: ansible_facts['os_distribution'] == "Ubuntu"
